Repository gardener/aws-custom-route-controller, pull requests merged in 2024-10, with the labels that each got.

#34 Introduce `gosec` for Static Application Security Testing (SAST)
  .gitignore
  Makefile
  go.mod
  hack/sast.sh
  hack/tools/install-gosec.sh
  hack/tools/tools.mk
Labels: area/compliance, area/networking, area/security, kind/enhancement, needs/ok-to-test, needs/review, size/m

#35 Add SAST logs to OCM component descriptor
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/xs

#38 Update kubernetes and other dependencies
  go.mod
  go.sum
Labels: needs/ok-to-test, needs/review, size/m
